import {
  InstituteSettings,
  SiteStatistic,
  Course,
  Project,
  Faculty,
  StudentAchievement,
  GalleryAlbum,
  EventItem,
  Testimonial,
  Enquiry,
  AdmissionApplication,
  FAQItem,
  AdminUser,
} from "@/types";

export const initialAdminUsers: AdminUser[] = [
  {
    id: "admin-user-001",
    email: "admin@ylcc.edu.in",
    name: "YLCC Administrator",
    role: "super_admin",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "admin-user-002",
    email: "editor@ylcc.edu.in",
    name: "Academics Editor",
    role: "editor",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialSettings: InstituteSettings = {
  id: "institute-settings-001",
  name: "YLCC",
  fullForm: "Youth Leadership & Career Campus",
  tagline: "Empowering Next-Generation Tech Leaders & Industry Innovators",
  instituteType: "Premier Institute for Advanced Computing, Artificial Intelligence & Career Excellence",
  location: "Bengaluru, Karnataka, India",
  address: "YLCC Campus, 4th Block, 80 Feet Road, Koramangala, Bengaluru, Karnataka 560034, India",
  phone: "+91 98765 43210",
  whatsapp: "+91 98765 43210",
  email: "contact@ylcc.edu.in",
  admissionsEmail: "admissions@ylcc.edu.in",
  officeHours: "Monday - Saturday: 8:30 AM - 7:30 PM (IST)",
  socialLinks: {
    instagram: "https://instagram.com/ylcc_official",
    linkedin: "https://linkedin.com/company/ylcc-campus",
    youtube: "https://youtube.com/@ylcc-tech",
    facebook: "https://facebook.com/ylcc.institute",
    github: "https://github.com/ylcc-campus",
  },
  announcementBar: {
    enabled: true,
    badge: "Admissions Open",
    text: "Summer 2026 Cohorts for Full-Stack AI & Cloud Architecture are now open! Limited merit scholarships available.",
    linkUrl: "/apply",
    linkText: "Apply Online",
  },
  heroConfig: {
    badge: "Transforming Engineering & Leadership Potential",
    titleLine1: "Build Real Systems.",
    titleHighlight: "Master Deep Tech.",
    titleLine2: "Accelerate Your Future.",
    description: "At YLCC, we bridge the gap between academic theory and high-impact industry engineering. Learn from senior architects, ship production-grade systems, and fast-track your journey into global technology roles.",
  },
  logoUrl: "/images/ylcc-logo.svg",
  mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3888.5835263625463!2d77.6253457759891!3d12.93448498737728!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bae14436573c739%3A0xb35749f7065f4ff!2sKoramangala%2C%20Bengaluru%2C%20Karnataka!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin",
};

export const initialSiteStatistics: SiteStatistic[] = [
  {
    id: "stat-1",
    label: "Graduates Trained",
    value: 12500,
    suffix: "+",
    description: "Equipped with industry-demanded engineering skills",
    iconName: "Users",
    order: 1,
  },
  {
    id: "stat-2",
    label: "Placement Rate",
    value: 94,
    suffix: "%",
    description: "Secured roles across global enterprises and high-growth startups",
    iconName: "TrendingUp",
    order: 2,
  },
  {
    id: "stat-3",
    label: "Hiring Partners",
    value: 180,
    suffix: "+",
    description: "Active industry recruitment and mentorship partners",
    iconName: "Building2",
    order: 3,
  },
  {
    id: "stat-4",
    label: "Student Projects Shipped",
    value: 450,
    suffix: "+",
    description: "Production deployed full-stack, AI, and cloud architectures",
    iconName: "Code2",
    order: 4,
  },
];

export const initialCourses: Course[] = [
  {
    id: "course-1",
    title: "Full-Stack Software Engineering & Microservices",
    slug: "full-stack-software-engineering",
    shortDescription: "Master modern web architectures with Next.js, Node.js, TypeScript, PostgreSQL, Docker, and scalable microservices.",
    fullDescription: "An intensive, hands-on immersion into modern enterprise web development. Starting from fundamental TypeScript typing and Next.js App Router patterns, you will construct distributed REST and GraphQL backends, optimize relational queries in PostgreSQL, orchestrate microservices with Docker, and implement automated CI/CD pipelines.",
    category: "Software Engineering",
    level: "All Levels",
    mode: "Hybrid",
    duration: "20 Weeks",
    durationWeeks: 20,
    fees: 65000,
    discountedFees: 49999,
    instructorName: "Arjun Venkataraman",
    instructorRole: "Principal Architect, ex-Amazon & Tech Evangelist",
    instructorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    batchTiming: "Weekdays (7:00 PM - 9:30 PM) / Weekends (10:00 AM - 4:00 PM)",
    startDate: "2026-05-15",
    availableSeats: 8,
    totalSeats: 30,
    isFeatured: true,
    isPublished: true,
    hasCertificate: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    toolsAndTech: ["TypeScript", "Next.js", "React 19", "Node.js", "PostgreSQL", "Prisma", "Docker", "Redis", "Tailwind CSS"],
    learningOutcomes: [
      "Architect clean full-stack Next.js applications using Server Actions and App Router",
      "Model normalized relational schemas and optimize complex SQL queries in PostgreSQL",
      "Deploy containerized microservices behind Nginx reverse proxies with Docker",
      "Implement secure JWT and OAuth2 session lifecycles with enterprise RBAC",
      "Build real-time collaborative applications using WebSockets and Redis pub/sub",
    ],
    eligibility: [
      "Basic programming exposure in any language (JavaScript, Python, C++, or Java)",
      "Enthusiasm to dedicate 10-15 hours per week on hands-on coding assignments",
      "Final-year college students, recent graduates, or working engineers seeking role transitions",
    ],
    modules: [
      {
        id: "mod-1",
        title: "Modern JavaScript & TypeScript Mastery",
        durationWeeks: 4,
        description: "Deep dive into JS runtime, asynchronous programming, event loop, and strict TypeScript types.",
        topics: ["Closures & Prototypes", "Generics & Conditional Types", "Async/Await internals", "Functional Programming paradigms"],
      },
      {
        id: "mod-2",
        title: "Frontend Engineering with Next.js & React 19",
        durationWeeks: 5,
        description: "Building resilient user experiences with component design systems, state machines, and SSR/SSG.",
        topics: ["React 19 Hooks & Server Components", "Next.js App Router & Routing Cache", "Tailwind CSS Design Systems", "State Management & Optimistic UI"],
      },
      {
        id: "mod-3",
        title: "Backend Microservices & Relational Databases",
        durationWeeks: 6,
        description: "Architecting high-throughput backend APIs with Node.js, Express, PostgreSQL, and Redis.",
        topics: ["REST & GraphQL API Architecture", "PostgreSQL Indexing & Transactions", "Caching Strategies with Redis", "Authentication, Sessions & JWT"],
      },
      {
        id: "mod-4",
        title: "DevOps, Containerization & Capstone Deployment",
        durationWeeks: 5,
        description: "Packaging applications with Docker, establishing GitHub Actions CI/CD pipelines, and cloud deployment.",
        topics: ["Docker & Multi-stage builds", "Automated CI/CD Workflows", "Vercel & AWS Deployment", "Final Capstone Project Defense"],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "course-2",
    title: "Applied Generative AI, LLMs & Machine Learning",
    slug: "applied-generative-ai-and-machine-learning",
    shortDescription: "Build real-world intelligent systems using Python, PyTorch, LangChain, LlamaIndex, Vector Databases, and Fine-Tuning.",
    fullDescription: "Bridge the frontier between foundational AI theory and practical production LLM applications. From statistical learning algorithms and deep neural nets to modern Retrieval-Augmented Generation (RAG) architectures and agentic AI workflows, you will design systems that reason, automate, and deliver business value.",
    category: "Data & AI",
    level: "Intermediate",
    mode: "Hybrid",
    duration: "18 Weeks",
    durationWeeks: 18,
    fees: 72000,
    discountedFees: 54999,
    instructorName: "Dr. Rohini Sundaram",
    instructorRole: "AI Research Fellow & Former Chief Data Scientist",
    instructorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    batchTiming: "Weekends (9:30 AM - 3:30 PM)",
    startDate: "2026-05-20",
    availableSeats: 6,
    totalSeats: 25,
    isFeatured: true,
    isPublished: true,
    hasCertificate: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=1200&q=80",
    toolsAndTech: ["Python", "PyTorch", "Hugging Face", "LangChain", "LlamaIndex", "Pinecone", "ChromaDB", "FastAPI"],
    learningOutcomes: [
      "Implement machine learning regression, classification, and clustering from first principles",
      "Fine-tune open-weight LLMs (Mistral, LLaMA) with LoRA and QLoRA techniques",
      "Architect enterprise RAG pipelines with semantic search and vector embeddings",
      "Deploy scalable AI inference endpoints using FastAPI and vLLM",
    ],
    eligibility: [
      "Familiarity with Python syntax and foundational college mathematics (linear algebra)",
      "Desire to build and ship real intelligent applications",
    ],
    modules: [
      {
        id: "mod-201",
        title: "Machine Learning & Statistical Foundations",
        durationWeeks: 4,
        description: "Core algorithms, gradient descent, feature engineering, and model evaluation metrics.",
        topics: ["NumPy & Pandas for Data Science", "Supervised Learning models", "Unsupervised Clustering & PCA", "Validation & Cross-entropy loss"],
      },
      {
        id: "mod-202",
        title: "Deep Learning & Transformer Architectures",
        durationWeeks: 5,
        description: "Understanding neural representations, attention mechanisms, and the Transformer decoder architecture.",
        topics: ["PyTorch Neural Network construction", "Self-Attention & Multi-Head Attention", "BERT vs GPT architectures", "Tokenization & Embeddings"],
      },
      {
        id: "mod-203",
        title: "Generative AI, RAG & Vector Databases",
        durationWeeks: 5,
        description: "Constructing reliable LLM applications, retrieval pipelines, hybrid search, and hallucination reduction.",
        topics: ["LangChain & LlamaIndex Pipelines", "Pinecone & Chroma Vector Stores", "Chunking Strategies & Semantic Routing", "Prompt Engineering & Evaluation"],
      },
      {
        id: "mod-204",
        title: "Autonomous Agents & Production AI Serving",
        durationWeeks: 4,
        description: "Deploying production LLM agents with tool-calling capabilities, safety guardrails, and latency optimization.",
        topics: ["Function Calling & Agent Loops", "LoRA/QLoRA Fine-tuning", "vLLM & Dockerized Serving", "AI Safety & Guardrails"],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "course-3",
    title: "Cloud Infrastructure, Kubernetes & DevOps",
    slug: "cloud-infrastructure-and-devops",
    shortDescription: "Architect highly available, automated cloud platforms using AWS, Kubernetes, Terraform, Prometheus, and GitHub Actions.",
    fullDescription: "Equip yourself with the skills needed to design, secure, and operate mission-critical cloud platforms. Learn infrastructure-as-code through Terraform, manage container clusters with Kubernetes, observe system health with Prometheus and Grafana, and automate zero-downtime blue-green deployments.",
    category: "Cloud & DevOps",
    level: "Intermediate",
    mode: "Online",
    duration: "16 Weeks",
    durationWeeks: 16,
    fees: 58000,
    discountedFees: 44999,
    instructorName: "Vikramaditya Nair",
    instructorRole: "Staff Site Reliability Engineer, ex-Cisco",
    instructorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    batchTiming: "Weekdays (8:00 PM - 10:00 PM)",
    startDate: "2026-06-01",
    availableSeats: 12,
    totalSeats: 30,
    isFeatured: false,
    isPublished: true,
    hasCertificate: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    toolsAndTech: ["AWS", "Terraform", "Kubernetes", "Docker", "Helm", "Prometheus", "Grafana", "GitHub Actions", "Linux"],
    learningOutcomes: [
      "Provision multi-region AWS cloud topologies with declarative Terraform scripts",
      "Manage containerized workloads with Kubernetes Pods, Deployments, Services, and Ingress",
      "Build automated CI/CD pipelines with automated security scanning and unit testing",
      "Establish site observability with custom metrics, tracing, and alerting",
    ],
    eligibility: [
      "Basic Linux CLI familiarity",
      "Understanding of fundamental networking concepts (DNS, TCP/IP, HTTP/HTTPS)",
    ],
    modules: [
      {
        id: "mod-301",
        title: "Linux Systems & Cloud Foundations (AWS)",
        durationWeeks: 4,
        description: "Mastering Linux administration, VPC networking, IAM security, and EC2/S3 architectures.",
        topics: ["Linux Shell Scripting & Permissions", "AWS VPC, Subnets & Route Tables", "IAM Policies & Least Privilege", "Storage Architectures: S3 & EBS"],
      },
      {
        id: "mod-302",
        title: "Infrastructure as Code with Terraform",
        durationWeeks: 4,
        description: "State management, reusable Terraform modules, variables, and automated drift prevention.",
        topics: ["Terraform HCL syntax", "Remote State in S3 with DynamoDB locking", "Modular Cloud Architecture", "Terraform Cloud & CI triggers"],
      },
      {
        id: "mod-303",
        title: "Kubernetes Orchestration & Helm Packaging",
        durationWeeks: 5,
        description: "Operating production Kubernetes clusters, ConfigMaps, Secrets, Ingress controllers, and Helm charts.",
        topics: ["K8s Architecture & Control Plane", "StatefulSets vs Deployments", "Ingress-NGINX & TLS automation", "Helm Chart writing"],
      },
      {
        id: "mod-304",
        title: "CI/CD Automation & Full-Stack Observability",
        durationWeeks: 3,
        description: "Building production deployment pipelines and observability dashboards with Prometheus & Grafana.",
        topics: ["GitHub Actions Workflows", "Prometheus & Node Exporter", "Grafana Dashboards & Alertmanager", "Zero-Downtime Rollouts"],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "course-4",
    title: "Data Analytics, SQL & Business Intelligence",
    slug: "data-analytics-and-business-intelligence",
    shortDescription: "Transform raw organizational data into actionable decision frameworks with Advanced SQL, Python, Tableau, and PowerBI.",
    fullDescription: "Master the art and science of quantitative decision-making. Learn to write complex SQL window functions, clean and reshape massive datasets in Python Pandas, develop executive dashboards in PowerBI and Tableau, and communicate insights that drive business growth.",
    category: "Data & AI",
    level: "Beginner",
    mode: "Hybrid",
    duration: "14 Weeks",
    durationWeeks: 14,
    fees: 48000,
    discountedFees: 36999,
    instructorName: "Meera Krishnan",
    instructorRole: "Lead Business Intelligence Consultant, ex-Deloitte",
    instructorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
    batchTiming: "Weekdays (6:30 PM - 8:30 PM)",
    startDate: "2026-05-25",
    availableSeats: 15,
    totalSeats: 35,
    isFeatured: false,
    isPublished: true,
    hasCertificate: true,
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    toolsAndTech: ["SQL", "Python", "Pandas", "PowerBI", "Tableau", "Excel", "PostgreSQL"],
    learningOutcomes: [
      "Author complex analytical SQL queries using CTEs, window functions, and pivot tables",
      "Perform statistical exploratory data analysis (EDA) using Python Pandas and Seaborn",
      "Build interactive, executive-ready dashboards in PowerBI and Tableau",
      "Synthesize data findings into strategic business recommendations",
    ],
    eligibility: [
      "No prior coding experience required; comfort with basic math and spreadsheets is sufficient",
    ],
    modules: [
      {
        id: "mod-401",
        title: "Advanced SQL for Data Analysis",
        durationWeeks: 4,
        description: "Mastering joins, subqueries, analytical window functions, and indexing in PostgreSQL.",
        topics: ["Relational Data Modeling", "Aggregations & Grouping", "Window Functions (RANK, DENSE_RANK, LAG, LEAD)", "Common Table Expressions"],
      },
      {
        id: "mod-402",
        title: "Python for Data Analysis & Visualization",
        durationWeeks: 5,
        description: "Data wrangling, cleaning missing values, and visual storytelling with Pandas and Seaborn.",
        topics: ["NumPy arrays & vectorization", "Pandas DataFrames manipulation", "Statistical hypothesis testing", "Data storytelling with Matplotlib & Seaborn"],
      },
      {
        id: "mod-403",
        title: "Executive BI Dashboards (PowerBI & Tableau)",
        durationWeeks: 5,
        description: "Building automated reports, DAX calculations, and interactive visual hierarchies.",
        topics: ["PowerBI Star Schemas & DAX", "Tableau Calculated Fields & LOD expressions", "Drill-down charts & KPIs", "Live Client Capstone Presentation"],
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialProjects: Project[] = [
  {
    id: "proj-1",
    title: "MediSync AI: Autonomous Clinical Triage & Diagnostic Assistant",
    slug: "medisync-ai-clinical-triage",
    shortDescription: "An AI-powered emergency clinical decision support system that ingests patient vital signs and lab results to assist doctors with triage prioritization.",
    fullDescription: "MediSync AI is an end-to-end clinical workflow assistant designed by our students under mentor guidance. Built using Next.js 15, FastAPI, LangChain, and a fine-tuned clinical LLM, the system processes multimodal patient histories, analyzes ECG/radiology structured reports, highlights potential drug contraindications, and computes real-time patient acuity scores for emergency rooms.",
    category: "AI & Machine Learning",
    technologies: ["Next.js", "TypeScript", "FastAPI", "Python", "PyTorch", "PostgreSQL", "LangChain", "Tailwind CSS"],
    topics: [
      "Multimodal Patient History & Vitals Ingestion",
      "ECG & Radiology Diagnostic Report Extraction",
      "Real-Time Emergency Triage Acuity Scoring (ESI)",
      "Automated Drug-Drug Contraindication Warnings",
      "Doctor Sign-Off & HIPAA Audit Logging Workflow",
    ],
    contributors: [
      { name: "Siddharth Rao", role: "AI & LLM Engineer", linkedinUrl: "https://linkedin.com" },
      { name: "Priya Sharma", role: "Full-Stack Frontend Developer", linkedinUrl: "https://linkedin.com" },
      { name: "Tanmay Deshmukh", role: "Backend & Systems Architect", linkedinUrl: "https://linkedin.com" },
    ],
    mentorName: "Dr. Rohini Sundaram",
    mentorDesignation: "Chief AI Mentor & Former Chief Data Scientist",
    coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80",
    ],
    demoVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    liveDemoUrl: "https://medisync-demo.ylcc.edu.in",
    githubUrl: "https://github.com/ylcc-campus/medisync-ai",
    pdfReportUrl: "/uploads/medisync-project-report.pdf",
    zipSourceUrl: "/uploads/medisync-source-code.zip",
    completionDate: "2026-03-10",
    academicBatch: "Winter Cohort 2025-26",
    isFeatured: true,
    isPublished: true,
    seoTitle: "MediSync AI - Clinical Triage Assistant | YLCC Student Project",
    seoDescription: "Explore MediSync AI, an autonomous clinical triage assistant built by YLCC student engineers using Next.js, FastAPI, and LangChain.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "proj-2",
    title: "FinPulse: Real-Time Algorithmic Trading & Risk Analytics Engine",
    slug: "finpulse-algorithmic-trading-engine",
    shortDescription: "A low-latency financial analytics platform capable of streaming 50,000 tick events/sec with sub-millisecond risk evaluation.",
    fullDescription: "Developed to tackle the challenges of high-frequency market data, FinPulse utilizes Go and WebSockets for data ingestion, TimescaleDB for time-series persistence, and a reactive Next.js frontend with Canvas-based candlestick visualizers. The engine tests complex momentum and arbitrage strategies against historical market data with realistic slippage modeling.",
    category: "Full-Stack Web",
    technologies: ["Go", "Next.js", "TypeScript", "TimescaleDB", "Redis", "WebSockets", "Docker", "Tailwind CSS"],
    topics: [
      "Sub-Millisecond Tick Event Ingestion (50K events/sec)",
      "Dynamic Canvas-Powered Candlestick Visualizer",
      "Order Book Slippage & Arbitrage Strategy Backtesting",
      "Distributed In-Memory Redis Caching Layer",
      "TimescaleDB High-Frequency Data Chunk Compression",
    ],
    contributors: [
      { name: "Aditya Verma", role: "High-Performance Systems Lead", linkedinUrl: "https://linkedin.com" },
      { name: "Kavya Murthy", role: "Data Visualization & UI Lead", linkedinUrl: "https://linkedin.com" },
    ],
    mentorName: "Arjun Venkataraman",
    mentorDesignation: "Principal Architect, ex-Amazon",
    coverImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1642543492481-44e81e3914a7?auto=format&fit=crop&w=1200&q=80",
    ],
    demoVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    liveDemoUrl: "https://finpulse.ylcc.edu.in",
    githubUrl: "https://github.com/ylcc-campus/finpulse-engine",
    pdfReportUrl: "/uploads/finpulse-architecture.pdf",
    zipSourceUrl: "/uploads/finpulse-code.zip",
    completionDate: "2026-02-18",
    academicBatch: "Autumn Cohort 2025",
    isFeatured: true,
    isPublished: true,
    seoTitle: "FinPulse - Real-time Trading Engine | YLCC Student Showcase",
    seoDescription: "Discover FinPulse, a sub-millisecond risk and trading engine created by YLCC students using Go, WebSockets, and TimescaleDB.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "proj-3",
    title: "CloudOps Sentinel: Multi-Cloud Drift & Security Auditor",
    slug: "cloudops-sentinel-security-auditor",
    shortDescription: "An automated infrastructure monitoring agent detecting resource misconfigurations, IAM leaks, and cost anomalies across AWS & GCP.",
    fullDescription: "CloudOps Sentinel acts as an automated security watchdog for enterprise cloud environments. The tool compares live cloud infrastructure state with Git-managed Terraform manifests, instantly flagging unapproved manual changes, public S3 buckets, and non-compliant security groups with one-click remediation pull requests.",
    category: "Cloud Architecture",
    technologies: ["Terraform", "AWS SDK", "Go", "Docker", "Next.js", "PostgreSQL", "GitHub API"],
    topics: [
      "GitOps Infrastructure Drift Detection Against Terraform",
      "Automated IAM Least-Privilege Role & Policy Auditor",
      "Multi-Cloud S3 Bucket & Security Group Risk Scanner",
      "Real-Time Cloud Cost Anomaly Alerts & Right-Sizing",
      "One-Click GitHub Automated Remediation Pull Requests",
    ],
    contributors: [
      { name: "Rahul Nambiar", role: "DevOps & Cloud Engineer", linkedinUrl: "https://linkedin.com" },
      { name: "Nisha Patel", role: "Full-Stack Engineer", linkedinUrl: "https://linkedin.com" },
    ],
    mentorName: "Vikramaditya Nair",
    mentorDesignation: "Staff SRE, ex-Cisco",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    ],
    demoVideoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    liveDemoUrl: "https://sentinel.ylcc.edu.in",
    githubUrl: "https://github.com/ylcc-campus/cloudops-sentinel",
    completionDate: "2026-01-25",
    academicBatch: "Autumn Cohort 2025",
    isFeatured: false,
    isPublished: true,
    seoTitle: "CloudOps Sentinel - Automated Infrastructure Auditor | YLCC",
    seoDescription: "CloudOps Sentinel monitors AWS & GCP configurations to prevent drift and cost anomalies.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "proj-4",
    title: "AgriVision: Edge IoT Crop Disease Detection System",
    slug: "agrivision-edge-crop-disease-detection",
    shortDescription: "Deploying lightweight vision models on Raspberry Pi edge hardware to detect leaf blights and pest infestations in remote farmlands.",
    fullDescription: "Built for farmers in low-connectivity rural zones, AgriVision runs quantized MobileNet and YOLOv8 models locally on edge devices. It captures high-resolution crop imagery, classifies 38 common crop pathologies within 400ms, and provides localized audio and SMS remedy advice without requiring active internet access.",
    category: "IoT & Hardware",
    technologies: ["Python", "TensorFlow Lite", "Raspberry Pi", "React Native", "FastAPI", "SQLite"],
    topics: [
      "Quantized YOLOv8 Edge Leaf Pathology Classification",
      "Offline-First SQLite Disease & Treatment Knowledgebase",
      "Sub-400ms Real-Time Camera Hardware Frame Processing",
      "Multi-lingual Localized Voice & SMS Farmer Advisory",
      "Low-Power Solar-Assisted Enclosure Optimization",
    ],
    contributors: [
      { name: "Deepak S.", role: "Embedded & Edge AI Lead", linkedinUrl: "https://linkedin.com" },
      { name: "Ananya Joshi", role: "Mobile Application Developer", linkedinUrl: "https://linkedin.com" },
    ],
    mentorName: "Dr. Rohini Sundaram",
    mentorDesignation: "Chief AI Mentor",
    coverImage: "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80",
    galleryImages: [
      "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1200&q=80",
    ],
    githubUrl: "https://github.com/ylcc-campus/agrivision-iot",
    completionDate: "2025-11-30",
    academicBatch: "Monsoon Cohort 2025",
    isFeatured: false,
    isPublished: true,
    seoTitle: "AgriVision - Edge AI Crop Diagnostics | YLCC Project Showcase",
    seoDescription: "An edge computing project diagnosing crop diseases using quantized neural networks on Raspberry Pi.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialFaculty: Faculty[] = [
  {
    id: "fac-1",
    name: "Arjun Venkataraman",
    designation: "Head of Software Engineering & Systems",
    qualifications: "M.Tech in Computer Science (IISc Bangalore), B.Tech (NIT Trichy)",
    expertise: ["Distributed Systems", "Full-Stack Architecture", "High-Throughput Databases", "Cloud Native"],
    experienceYears: 14,
    bio: "Former Principal Architect at Amazon and tech lead at high-scale Indian unicorns. Arjun specializes in turning aspiring programmers into pragmatic, production-focused system architects who write robust and testable software.",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80",
    email: "arjun.v@ylcc.edu.in",
    socialLinks: {
      linkedin: "https://linkedin.com/in/arjun-venkataraman",
      github: "https://github.com/arjun-v-eng",
    },
    coursesTaught: ["Full-Stack Software Engineering & Microservices"],
    isFeatured: true,
    order: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fac-2",
    name: "Dr. Rohini Sundaram",
    designation: "Dean of Artificial Intelligence & Data Sciences",
    qualifications: "Ph.D. in Machine Learning (IIT Madras), Postdoctoral Fellow (NUS Singapore)",
    expertise: ["Generative AI", "Large Language Models", "Natural Language Processing", "Computer Vision"],
    experienceYears: 16,
    bio: "Dr. Rohini has published over 25 peer-reviewed papers in top ML conferences (NeurIPS, CVPR) and led applied AI research teams across healthcare and financial services. She spearheads YLCC's advanced AI curriculum.",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    email: "rohini.s@ylcc.edu.in",
    socialLinks: {
      linkedin: "https://linkedin.com/in/dr-rohini-sundaram",
      twitter: "https://twitter.com/rohini_ai",
    },
    coursesTaught: ["Applied Generative AI, LLMs & Machine Learning"],
    isFeatured: true,
    order: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fac-3",
    name: "Vikramaditya Nair",
    designation: "Senior Mentor - Cloud Infrastructure & SRE",
    qualifications: "B.Tech in Information Technology, AWS Certified Solutions Architect Professional",
    expertise: ["Kubernetes", "Multi-Cloud Security", "Infrastructure as Code", "Site Reliability"],
    experienceYears: 12,
    bio: "Vikram has managed enterprise infrastructure hosting over 10 million concurrent users at Cisco and global SaaS providers. He mentors YLCC cohorts on reliability engineering, security postures, and incident response.",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=600&q=80",
    email: "vikram.nair@ylcc.edu.in",
    socialLinks: {
      linkedin: "https://linkedin.com/in/vikram-sre-nair",
      github: "https://github.com/vikramaditya-nair",
    },
    coursesTaught: ["Cloud Infrastructure, Kubernetes & DevOps"],
    isFeatured: true,
    order: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "fac-4",
    name: "Meera Krishnan",
    designation: "Director of Analytics & Executive Decision Systems",
    qualifications: "MBA (IIM Calcutta), B.E. in Electronics & Communication",
    expertise: ["Business Analytics", "SQL Architecture", "Tableau & PowerBI", "Product Metrics"],
    experienceYears: 10,
    bio: "Meera previously led commercial business intelligence teams at Deloitte and Flipkart. She bridges technical data wrangling with board-level storytelling, guiding students to make measurable business impact.",
    photoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=600&q=80",
    email: "meera.k@ylcc.edu.in",
    socialLinks: {
      linkedin: "https://linkedin.com/in/meera-krishnan-bi",
    },
    coursesTaught: ["Data Analytics, SQL & Business Intelligence"],
    isFeatured: true,
    order: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialAchievements: StudentAchievement[] = [
  {
    id: "ach-1",
    studentName: "Aditya Verma & Kavya Murthy",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    achievementTitle: "1st Place - National FinTech Hackathon 2026",
    description: "Built the lowest-latency order execution engine prototype among 350+ engineering teams nationwide, awarded ₹2,50,000 cash prize.",
    courseName: "Full-Stack Software Engineering",
    batch: "Cohort 2025-26",
    companyOrOrganizer: "National Payment Systems & FinTech Council",
    achievementDate: "2026-02-15",
    evidenceUrl: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&w=800&q=80",
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ach-2",
    studentName: "Siddharth Rao",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80",
    achievementTitle: "Placed as Lead AI Systems Engineer at TechCorp",
    description: "Transitioned from non-tech background to securing a high-impact role building production RAG systems with a 180% compensation uplift.",
    courseName: "Applied Generative AI & Machine Learning",
    batch: "Cohort 2025",
    companyOrOrganizer: "Global Enterprise TechCorp",
    achievementDate: "2026-01-20",
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "ach-3",
    studentName: "Divya Balakrishnan",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
    achievementTitle: "Best Open-Source Contribution at PyCon India",
    description: "Authored an open-source benchmarking tool for vector embedding models adopted by over 2,000 developers globally.",
    courseName: "Applied Generative AI & Machine Learning",
    batch: "Cohort 2025",
    companyOrOrganizer: "PyCon India Community",
    achievementDate: "2025-10-14",
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialGalleryAlbums: GalleryAlbum[] = [
  {
    id: "album-1",
    title: "YLCC Annual 48-Hour Hackathon 2026",
    slug: "ylcc-annual-hackathon-2026",
    description: "48 hours of collaborative design, rapid prototyping, and high-energy mentorship in our Bengaluru innovation center.",
    category: "Hackathons",
    coverImageUrl: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1200&q=80",
    items: [
      {
        id: "item-101",
        albumId: "album-1",
        title: "Late night coding sprint",
        imageUrl: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1200&q=80",
        caption: "Teams collaborating on cloud-native deployments during hour 32.",
        takenAt: "2026-02-14",
      },
      {
        id: "item-102",
        albumId: "album-1",
        title: "Mentor walkthrough & code reviews",
        imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
        caption: "Arjun Venkataraman reviewing architectural trade-offs with finalists.",
        takenAt: "2026-02-14",
      },
      {
        id: "item-103",
        albumId: "album-1",
        title: "Final project presentations",
        imageUrl: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=1200&q=80",
        caption: "Student teams pitching to an industry jury of VCs and CTOs.",
        takenAt: "2026-02-15",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "album-2",
    title: "High-Tech Computer Labs & Collaborative Spaces",
    slug: "campus-infrastructure-and-labs",
    description: "Take a visual tour inside YLCC's purpose-built modern coding labs, ergonomic maker bays, and seminar suites.",
    category: "Campus Life",
    coverImageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    items: [
      {
        id: "item-201",
        albumId: "album-2",
        title: "Collaborative Engineering Bay",
        imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
        caption: "Dual-monitor developer workstations equipped for pair programming.",
        takenAt: "2026-01-10",
      },
      {
        id: "item-202",
        albumId: "album-2",
        title: "Interactive Classroom & Lecture Suite",
        imageUrl: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80",
        caption: "Acoustically tuned lecture theatre with 4K projection and live streaming.",
        takenAt: "2026-01-10",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "album-3",
    title: "Graduation Convocation & Awards Ceremony",
    slug: "convocation-and-awards",
    description: "Celebrating our successful cohort graduates stepping into leading software engineering and AI positions.",
    category: "Convocations",
    coverImageUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
    items: [
      {
        id: "item-301",
        albumId: "album-3",
        title: "Awarding Capstone Excellence Medals",
        imageUrl: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1200&q=80",
        caption: "Director presenting Capstone Honors to the Autumn Cohort toppers.",
        takenAt: "2025-12-20",
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialEvents: EventItem[] = [
  {
    id: "event-1",
    title: "Building Production-Ready LLM Agents with Tool Calling",
    slug: "building-production-llm-agents-workshop",
    type: "Workshop",
    shortDescription: "A 3-hour intensive masterclass on orchestrating multi-agent systems, memory persistence, and guardrails.",
    fullDescription: "Join Dr. Rohini Sundaram for an interactive hands-on code-along. We will move beyond trivial chatbots to construct an agent capable of querying SQL databases, inspecting REST APIs, handling tool errors gracefully, and returning verified structured JSON responses.",
    bannerUrl: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?auto=format&fit=crop&w=1200&q=80",
    eventDate: "2026-05-10",
    startTime: "10:30 AM",
    endTime: "01:30 PM",
    venue: "YLCC Koramangala Auditorium & Live Stream",
    mode: "Hybrid",
    registrationUrl: "/apply",
    isRegistrationOpen: true,
    isFeatured: true,
    isPublished: true,
    speakerName: "Dr. Rohini Sundaram",
    speakerDesignation: "Dean of AI & Data Sciences, YLCC",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "event-2",
    title: "System Design for High Scale: The 100K RPS Architecture",
    slug: "system-design-for-high-scale-webinar",
    type: "Webinar",
    shortDescription: "Learn how modern cloud companies design distributed systems that survive massive traffic spikes.",
    fullDescription: "Unpack caching hierarchies, database sharding, asynchronous queues with Kafka/RabbitMQ, and resilience patterns (circuit breakers, rate limiting) with ex-Amazon architect Arjun Venkataraman.",
    bannerUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&w=1200&q=80",
    eventDate: "2026-05-28",
    startTime: "07:00 PM",
    endTime: "09:00 PM",
    venue: "Online via Zoom & YouTube Live",
    mode: "Online",
    registrationUrl: "/apply",
    isRegistrationOpen: true,
    isFeatured: true,
    isPublished: true,
    speakerName: "Arjun Venkataraman",
    speakerDesignation: "Principal Architect, YLCC",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "event-3",
    title: "YLCC Summer Tech Hackathon & Innovation Expo 2026",
    slug: "ylcc-summer-tech-hackathon-2026",
    type: "Hackathon",
    shortDescription: "36-hour offline hackathon with ₹3,00,000 prize pool and direct spot-interview opportunities with hiring partners.",
    fullDescription: "Open to student developers, recent graduates, and early professionals. Form teams of 2-4 and build solutions in FinTech, HealthTech, AI Agents, or Green Energy. Mentors from top startups will be available on-site.",
    bannerUrl: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=1200&q=80",
    eventDate: "2026-06-20",
    startTime: "09:00 AM",
    endTime: "09:00 PM (Next Day)",
    venue: "YLCC Campus, Koramangala, Bengaluru",
    mode: "In-Person",
    registrationUrl: "/apply",
    isRegistrationOpen: true,
    isFeatured: false,
    isPublished: true,
    speakerName: "Industry Jury Panel",
    speakerDesignation: "CTOs & Engineering Leaders",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: "test-1",
    studentName: "Anandita Sen",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    courseName: "Full-Stack Software Engineering",
    batch: "Class of 2025",
    currentRole: "Software Development Engineer II",
    company: "Walmart Global Tech",
    rating: 5,
    content: "YLCC completely redefined how I view software engineering. Rather than shallow syntax tutorials, we were pushed to build distributed systems, design relational databases with complex constraints, and dockerize our applications. That depth directly helped me crack my SDE-2 interview.",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    isApproved: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "test-2",
    studentName: "Karthik Rajagopalan",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    courseName: "Applied Generative AI & Machine Learning",
    batch: "Class of 2025",
    currentRole: "Applied AI Engineer",
    company: "Fractal Analytics",
    rating: 5,
    content: "The mentor access at YLCC is unmatched. Having Dr. Rohini review my RAG pipeline architecture and teach us vector quantization gave me confidence that few courses anywhere can provide. Today, I'm deploying LLM workflows in production.",
    isApproved: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "test-3",
    studentName: "Sneha Mukherjee",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
    courseName: "Cloud Infrastructure & DevOps",
    batch: "Class of 2025",
    currentRole: "Cloud Platform Engineer",
    company: "Accenture Technology",
    rating: 5,
    content: "I started with a traditional IT support role and felt stagnant. YLCC's intense hands-on labs with Terraform, Kubernetes, and CI/CD pipelines gave me the tangible portfolio I needed. The career team worked tirelessly until I achieved my dream role.",
    isApproved: true,
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialFAQs: FAQItem[] = [
  {
    id: "faq-1",
    question: "How are YLCC programs different from conventional institutes or recorded video courses?",
    answer: "YLCC focuses on rigorous engineering realism. You do not merely watch videos or build toy calculators. You learn live from active industry practitioners (ex-Amazon, Cisco, Tier-1 researchers), write production code, participate in code reviews, ship microservices, and deploy multi-contributor capstone systems to real cloud environments.",
    category: "General",
    order: 1,
    isPublished: true,
  },
  {
    id: "faq-2",
    question: "Do you offer placement support or interview preparation?",
    answer: "Yes. Every YLCC enrolled student in professional tracks receives comprehensive career support: resume overhauls tailored for ATS, 1-on-1 mock technical interviews, system design drills, algorithmic problem solving sessions, and direct interview opportunities through our 180+ hiring partner network.",
    category: "Placements",
    order: 2,
    isPublished: true,
  },
  {
    id: "faq-3",
    question: "Can working professionals join YLCC batches?",
    answer: "Absolutely. We offer dedicated evening batches (7:00 PM - 9:30 PM IST) and comprehensive weekend immersion tracks (Saturday & Sunday) specifically structured so that working professionals can upskill without interrupting their jobs.",
    category: "Courses",
    order: 3,
    isPublished: true,
  },
  {
    id: "faq-4",
    question: "What is the admission and selection process at YLCC?",
    answer: "Our admission process is designed to ensure motivation and fit. Submit an application online, complete a brief diagnostic assessment on logical reasoning or basic programming, followed by a counseling discussion with an academic counselor to finalize your cohort and learning mode.",
    category: "Admissions",
    order: 4,
    isPublished: true,
  },
  {
    id: "faq-5",
    question: "Are certificates recognized by companies?",
    answer: "Yes, YLCC certificates are verifiable with unique cryptographic verification codes and showcase the specific capstone projects, hours of engineering, and verified competencies achieved during the program.",
    category: "General",
    order: 5,
    isPublished: true,
  },
  {
    id: "faq-6",
    question: "What hardware or software requirements do I need?",
    answer: "A modern laptop (Windows, macOS, or Linux) with at least 8GB RAM (16GB recommended for AI/Docker modules) and a stable internet connection. All cloud sandboxes, server instances, and developer tools needed are provided as part of the cohort.",
    category: "Courses",
    order: 6,
    isPublished: true,
  },
];

export const initialEnquiries: Enquiry[] = [
  {
    id: "enq-1",
    fullName: "Rohan Kulkarni",
    email: "rohan.k@gmail.com",
    phone: "+91 98451 23456",
    courseInterest: "Full-Stack Software Engineering & Microservices",
    subject: "Weekend batch timings & scholarship enquiry",
    message: "Hi team, I am currently working as a QA engineer and wish to transition into full-stack development. Could you provide details on the upcoming weekend cohort and fee structure?",
    status: "New",
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "enq-2",
    fullName: "Shalini Gupta",
    email: "shalini.g@outlook.com",
    phone: "+91 97112 34567",
    courseInterest: "Applied Generative AI, LLMs & Machine Learning",
    subject: "Prerequisites clarification for AI program",
    message: "I have 2 years of Python experience in backend development. I want to check if my mathematics foundation is sufficient for the LLM fine-tuning modules.",
    status: "Contacted",
    adminNotes: "Spoke with candidate on phone; scheduled diagnostic counseling session for Saturday.",
    createdAt: new Date(Date.now() - 3600000 * 26).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
];

export const initialApplications: AdmissionApplication[] = [
  {
    id: "app-1",
    fullName: "Manish Agarwal",
    email: "manish.agarwal99@gmail.com",
    phone: "+91 99887 76655",
    dateOfBirth: "2001-08-14",
    address: "Flat 302, Green Glen Layout, Bellandur, Bengaluru 560103",
    qualification: "B.Tech in Computer Science (2024)",
    selectedCourse: "Full-Stack Software Engineering & Microservices",
    preferredMode: "Hybrid",
    preferredBatch: "Weekend",
    documentUrl: "/uploads/sample-resume.pdf",
    consentAgreed: true,
    status: "Under Review",
    adminNotes: "Profile looks solid. Graduated with 8.4 CGPA. Reviewing GitHub profile.",
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
  {
    id: "app-2",
    fullName: "Deepa Narayanan",
    email: "deepa.narayanan@yahoo.com",
    phone: "+91 91234 56780",
    dateOfBirth: "1999-12-05",
    address: "HSR Layout Sector 2, Bengaluru 560102",
    qualification: "B.E. in Electronics, 3 years industry experience",
    selectedCourse: "Applied Generative AI, LLMs & Machine Learning",
    preferredMode: "Online",
    preferredBatch: "Evening",
    consentAgreed: true,
    status: "Accepted",
    adminNotes: "Admitted into May 20 cohort with 10% Early Bird Scholarship.",
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
];
